# corina-service-staging-install-script.ps1
# Template copy of the per-clinic install script generated by samantha-analytics-web
# (src/app/api/install-script/route.ts, environment = staging).
# Fill in the clinic-specific values below. CorinaAgentToken is intentionally left blank;
# generate the real script (with a token) from the analytics script generator for actual installs.

$clinicTag        = ""   # e.g. "care-gp-chinatown"; leave empty for legacy no-tag install
$haloGuid         = ""   # the clinic's halo_site_id
$corinaAgentToken = ""   # left blank on purpose -- the generated script fills this in

# Ensure Admin
if (-not ([Security.Principal.WindowsPrincipal] `
            [Security.Principal.WindowsIdentity]::GetCurrent()).IsInRole(`
            [Security.Principal.WindowsBuiltInRole] "Administrator")) {
    Write-Error "You must run this script as Administrator."
    exit 1
}

Write-Host "[*] Running as Administrator"

# Force TLS 1.2 (required for GitHub; old .NET/PS 5.1 defaults to TLS 1.0)
try {
    $proto = [System.Net.ServicePointManager]::SecurityProtocol
    $tls12 = [System.Net.SecurityProtocolType]::Tls12
    if (($proto -band $tls12) -eq 0) {
        [System.Net.ServicePointManager]::SecurityProtocol = $proto -bor $tls12
    }
} catch {
    Write-Warning "Failed to enable TLS 1.2: $_"
}

Write-Host "`n[*] Configuring staging environment"
[Environment]::SetEnvironmentVariable("DOTNET_ENVIRONMENT", "Staging", [System.EnvironmentVariableTarget]::Machine)
Write-Host "    -> Set machine environment variable DOTNET_ENVIRONMENT=Staging"

# Registry key path
# Tagged installs keep settings in the instance subkey so the service can find them;
# legacy installs keep settings at the base key.
if ($clinicTag) {
    $regPath = "HKLM:\SOFTWARE\CareAI\CorinaService-Staging\$clinicTag"
} else {
    $regPath = "HKLM:\SOFTWARE\CareAI\CorinaService-Staging"
}
Write-Host "    -> Registry path: $regPath"
if (-not (Test-Path $regPath)) {
    New-Item -Path $regPath -Force | Out-Null
    Write-Host "    -> Created registry key"
}

# Set registry values for staging
$settings = [ordered]@{
    "SamanthaBaseUrl" = "https://backend.staging.caregp.com.au"
    "SamanthaUrl"     = "https://backend.staging.caregp.com.au/corina/analyse-with-gemini-for-corina-service"
    "HaloGuid"        = $haloGuid
}
# Only write the token when provided, so re-running this template never wipes a valid
# token already configured on the machine.
if (-not [string]::IsNullOrWhiteSpace($corinaAgentToken)) {
    $settings["CorinaAgentToken"] = $corinaAgentToken
}
if ($clinicTag) {
    $settings["ClinicTag"] = $clinicTag
}

Set-ItemProperty -Path $regPath -Name "DOTNET_ENVIRONMENT" -Value "Staging"
foreach ($name in $settings.Keys) {
    Set-ItemProperty -Path $regPath -Name $name -Value $settings[$name]
    Write-Host "    -> Set $name"
}

Write-Host "SUCCESS: Environment configuration complete (STAGING)"

# Run the installer script directly from GitHub
Write-Host "`n[*] Running installer from GitHub"
if ($clinicTag) {
    # CorinaRegistryInstance must be set on the process before install.ps1 runs
    $env:CorinaRegistryInstance = $clinicTag
    Write-Host "    -> CorinaRegistryInstance set to: $clinicTag"
} else {
    Write-Host "    -> CorinaRegistryInstance not set (legacy no-tag install)"
}
# install.ps1 sets this to $true as its very last line, so it is only $true
# when the installer ran all the way through (service running, task registered).
$corinaStagingInstallSucceeded = $false
$previousCorinaInstallerOutputIndent = $env:CorinaInstallerOutputIndent
$env:CorinaInstallerOutputIndent = "    "
try {
    irm https://raw.githubusercontent.com/Care-AI-Inc/careai-corina-service-staging-releases/main/install.ps1 | iex
} finally {
    if ($null -eq $previousCorinaInstallerOutputIndent) {
        Remove-Item Env:\CorinaInstallerOutputIndent -ErrorAction SilentlyContinue
    } else {
        $env:CorinaInstallerOutputIndent = $previousCorinaInstallerOutputIndent
    }
}

if ($corinaStagingInstallSucceeded -ne $true) {
    Write-Warning "Installer did not report success; keeping legacy registry values."
    exit 1
}
Write-Host "    -> Installer reported success"

Write-Host "`n[*] Cleaning up legacy registry values"
$legacySecretNames = @(
    "SupabaseUrl",
    "SupabaseServiceKey",
    "SupabaseRealtimeUrl",
    "AWS_LOG_BUCKET",
    "AWS_ACCESS_KEY_ID",
    "AWS_SECRET_ACCESS_KEY",
    "AWS_REGION"
)
foreach ($name in $legacySecretNames) {
    Remove-ItemProperty -Path $regPath -Name $name -ErrorAction SilentlyContinue
}
Write-Host "    -> Legacy registry values removed (if they existed)."

Write-Host "`nSUCCESS: Corina Service (Staging) install script complete."
